#!/bin/bash

wallpaper_directory="$HOME/Downloads"


menu_principal(){
  while true ; do
    resp=$(whiptail --title "MENU PRINCIPAL" --menu "Opciones disponibles:" 20 80 6 \
      "1" "Windows wallpaper"   \
      "2" "GNU-Linux wallpaper" \
      "3" "Salir"               \
      3>&1 1>&2 2>&3
    )

    if [ $? == 0 ] ; then
      case $resp in
        "1") change_wallpaper "1.png" ;;
        "2") change_wallpaper "2.png" ;;
        "3") break ;;
          *) continue ;;
      esac
    else
      break;
    fi
  done
}


change_wallpaper(){
  gsettings set org.gnome.desktop.background picture-uri "${wallpaper_directory}/$1" &
}



menu_principal
